In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer

In [ ]:
df= pd.read_csv("loan_regression_dataset.csv")

In [ ]:
df.head()

,Customer_ID,Name,Age,Years_Employed,Annual_Income,Credit_Score,Existing_Debt,Dependents,Loan_Amount_Approved
0,1,Arjun Singh,24.0,1.0,37300.0,726.0,9100.0,2.0,31800
1,2,Priya Rao,51.0,23.0,60900.0,694.0,30000.0,2.0,49000
2,3,Rohan Kumar,46.0,22.0,63000.0,712.0,14600.0,0.0,67900
3,4,Karthik Menon,38.0,12.0,46500.0,638.0,22700.0,1.0,33500
4,5,Pooja Das,37.0,13.0,52500.0,NaN,10800.0,1.0,51900

In [ ]:
df.shape

(200, 9)

In [ ]:
x=df.iloc[:,1:8].values
y=df.iloc[:,8].values

In [ ]:
df.isnull().sum()

Customer_ID              0
Name                     0
Age                      8
Years_Employed          10
Annual_Income           12
Credit_Score            10
Existing_Debt            9
Dependents               6
Loan_Amount_Approved     0
dtype: int64

In [ ]:
imputer= SimpleImputer(missing_values=np.nan, strategy="mean")
imputer.fit(x[:,1:8])
x[:,1:8]=imputer.transform(x[:,1:8])
print(x)

[['Arjun Singh' 24.0 1.0 ... 726.0 9100.0 2.0]
 ['Priya Rao' 51.0 23.0 ... 694.0 30000.0 2.0]
 ['Rohan Kumar' 46.0 22.0 ... 712.0 14600.0 0.0]
 ...
 ['Rohan Singh' 25.0 3.0 ... 581.0 12000.0 2.0]
 ['Manoj Sharma' 34.0 11.0 ... 603.0 7200.0 2.0]
 ['Ananya Joshi' 58.0 16.31578947368421 ... 655.0 2100.0 0.0]]

In [ ]:
print(df.dtypes)

Customer_ID               int64
Name                     object
Age                     float64
Years_Employed          float64
Annual_Income           float64
Credit_Score            float64
Existing_Debt           float64
Dependents              float64
Loan_Amount_Approved      int64
dtype: object

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [ ]:
##ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
#x=np.array(ct.fit_transform(x))

In [ ]:
#print(x)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [ ]:
print(x_train)

[['Manoj Nair' 39.0 16.0 ... 502.0 13800.0 4.0]
 ['Manoj Rao' 46.0 21.0 ... 590.0 13300.0 3.0]
 ['Deepa Sharma' 32.0 16.31578947368421 ... 800.0 100.0 4.0]
 ...
 ['Divya Iyer' 39.0 17.0 ... 746.0 9100.0 3.0]
 ['Vivaan Rao' 59.0 33.0 ... 648.0 5500.0 0.0]
 ['Rahul Das' 53.0 29.0 ... 570.0 24900.0 2.0]]

In [ ]:
print(x_test)

[['Pooja Reddy' 49.0 27.0 68300.0 677.7105263157895 12500.0 1.0]
 ['Aarav Nair' 27.0 5.0 18200.0 648.0 8100.0 0.0]
 ['Vivaan Singh' 55.0 31.0 63300.0 618.0 11000.0 0.0]
 ['Vivaan Kumar' 52.0 31.0 60700.0 561.0 29100.0 1.0]
 ['Deepa Sharma' 40.0 19.0 59500.0 535.0 4300.0 0.0]
 ['Manoj Sharma' 34.0 11.0 52800.0 603.0 7200.0 2.0]
 ['Meera Sharma' 32.0 7.0 41900.0 702.0 11800.0 0.0]
 ['Pooja Das' 37.0 13.0 52500.0 677.7105263157895 10800.0 1.0]
 ['Rahul Nair' 38.0 16.0 56100.0 659.0 11300.0 2.0]
 ['Suresh Rao' 34.0 13.0 48400.0 734.0 14500.0 1.0]
 ['Vivaan Patel' 40.416666666666664 0.0 22600.0 641.0 3600.0 2.0]
 ['Kavya Shetty' 53.0 29.0 70600.0 663.0 30600.0 1.958762886597938]
 ['Rahul Gowda' 59.0 33.0 68500.0 730.0 1300.0 2.0]
 ['Arjun Patel' 53.0 29.0 69300.0 670.0 34500.0 4.0]
 ['Aarav Iyer' 31.0 5.0 34500.0 825.0 900.0 3.0]
 ['Rahul Patel' 30.0 2.0 40500.0 727.0 8400.0 1.0]
 ['Meera Das' 51.0 25.0 69600.0 662.0 8800.0 2.0]
 ['Lakshmi Joshi' 23.0 0.0 24700.0 708.0 10500.0 2.0]
 ['Vikram Sharma' 44.0 16.0 47700.0 653.0 22200.0 1.0]
 ['Rahul Nair' 47.0 22.0 70000.0 690.0 2400.0 0.0]
 ['Priya Joshi' 28.0 4.0 52500.0 660.0 26200.0 1.0]
 ['Pooja Patel' 41.0 20.0 60300.0 639.0 21500.0 4.0]
 ['Manoj Shetty' 23.0 0.0 22100.0 669.0 7900.0 1.958762886597938]
 ['Divya Menon' 56.0 16.31578947368421 74200.0 745.0 6900.0 2.0]
 ['Karthik Reddy' 29.0 2.0 49900.0 783.0 16800.0 3.0]
 ['Sneha Patel' 36.0 14.0 43200.0 605.0 13000.0 0.0]
 ['Sneha Shetty' 31.0 8.0 35400.0 736.0 7000.0 4.0]
 ['Neha Reddy' 42.0 17.0 56300.0 627.0 800.0 3.0]
 ['Vivaan Sharma' 35.0 10.0 32300.0 777.0 2000.0 0.0]
 ['Ananya Verma' 53.0 28.0 62200.0 591.0 21100.0 3.0]
 ['Priya Joshi' 55.0 31.0 54604.255319148935 759.0 9400.0 0.0]
 ['Deepa Rao' 52.0 27.0 74000.0 700.0 30100.0 2.0]
 ['Rahul Joshi' 40.416666666666664 32.0 57200.0 607.0 25700.0 4.0]
 ['Pooja Rao' 27.0 1.0 39100.0 626.0 14200.0 1.0]
 ['Lakshmi Iyer' 48.0 22.0 70700.0 696.0 5800.0 0.0]
 ['Aarav Iyer' 47.0 23.0 41400.0 707.0 13500.0 1.0]
 ['Priya Menon' 48.0 20.0 60100.0 593.0 10400.0 1.0]
 ['Manoj Das' 40.416666666666664 0.0 54604.255319148935 622.0 13600.0 4.0]
 ['Deepa Naidu' 39.0 14.0 60100.0 652.0 8600.0 2.0]
 ['Priya Reddy' 40.416666666666664 27.0 72300.0 713.0 2800.0 4.0]]

In [ ]:
print(y_train)

[ 24900  47400  49700  65800  78400  44400  52200  55000  41100  58700
  49800  40600  34700  44600  41100  56100  17300  77300  97300  40100
  43700  24100  82400  68300  34300  73700  73600  74100  68800  63000
  51300  60100  67700  62600  61700  74800  47800  33300  45300  67900
  36500  35300  33300  88600  55400  66000  31500  21500  23300  78700
  38800  78000  47300  24100  67600  24700  28800  15900  77900  87800
  47500  67400  64700  68900  67900  57900  48300  72600  36600  55900
  31800  63900  42200  24600  34000  13800  53600  61700  27400  44400
  56300  38200  37400  63800  36300  56800  97000  80700  66900  42100
  12100  95200  45700  61300  50300  87400  49400  28000  23900 101800
  36400  31100  88600  35500  33800  33400  60100  31500  56200  83100
  78500  42100  31500  45200  52400  33500  44000  59200  14400  64900
  68900  57500  42900  56600  72900  24400  71900  74900  49000  44200
  32700  69200  57700  50300  57300  52100  29300  52800  33300  69700
  30500  61700  29500  39100  33600  36200  61100  80100  69200  89300
  61600  65200  62000  60500  73800  61800  15100  62300  86000  63300]

In [ ]:
print(y_test)

[60600 19600 62600 48300 44400 36800 47200 51900 57600 55300 17500 51700
 86200 46000 55300 43500 66000 23200 38400 82700 38700 52300 25000 90400
 48800 36500 38800 54800 54800 51700 78200 60800 39900 23400 80200 43100
 57000  7500 55800 83600]

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_test[:,1:8]=sc.fit_transform(x_test[:,1:8])
x_train[:,1:8]=sc.transform(x_train[:,1:8])

In [ ]:
print(x_test)

[['Pooja Reddy' 0.8080530753280657 1.0054908231677517 1.010081547790348
  0.08810721080673527 -0.003108128609236235 -0.5262635797554441]
 ['Aarav Nair' -1.418732017434036 -1.05377014735709 -2.255861041799744
  -0.39442027403830004 -0.5004087060870307 -1.2802896836886504]
 ['Vivaan Singh' 1.4153581006268208 1.3799019087177227 0.68413917357976
  -0.8816490895594162 -0.17264241638575709 -1.2802896836886504]
 ['Vivaan Kumar' 1.1117055879774431 1.3799019087177227 0.5146491389902541
  -1.8073838390495371 1.8730713227842613 -0.5262635797554441]
 ['Deepa Sharma' -0.10290446262006683 0.25666865206780926
  0.43642296917971307 -2.229648812501171 -0.929895568454217
  -1.2802896836886504]
 ['Manoj Sharma' -0.7102094879188219 -0.49215351903213317
  -0.0003398122624749271 -1.1252634973199744 -0.6021292787529432
  0.22776252417776222]
 ['Meera Sharma' -0.9126444963517402 -0.8665646045821044
  -0.7108941880415568 0.4825915938997092 -0.08222412957161263
  -1.2802896836886504]
 ['Pooja Das' -0.4065569752694443 -0.3049479762571476
  -0.019896354715110223 0.08810721080673527 -0.19524698808929322
  -0.5262635797554441]
 ['Rahul Nair' -0.3053394710529852 -0.02413966209466918
  0.21478215471651319 -0.21576970834722414 -0.13873555883045294
  0.22776252417776222]
 ['Suresh Rao' -0.7102094879188219 -0.3049479762571476
  -0.2871691015677924 1.0023023304555663 0.2229375884261249
  -0.5262635797554441]
 ['Vivaan Patel' -0.06073050252987574 -1.521784004294554
  -1.9690317524944265 -0.5081069976598938 -1.009011569416593
  0.22776252417776222]
 ['Kavya Shetty' 1.2129230921939023 1.1926963659427372 1.1600150399272184
  -0.15080586627774198 2.0426056105607824 0.19666866422175366]
 ['Rahul Gowda' 1.8202281174926576 1.5671074514927086 1.0231192427587714
  0.9373384883860842 -1.2689641440072585 0.22776252417776222]
 ['Arjun Patel' 1.2129230921939023 1.1926963659427372 1.0752700226324656
  -0.0371191426561482 2.4833947587797365 1.7358147320441752]
 ['Aarav Iyer' -1.0138620005681995 -1.05377014735709 -1.1932889018732271
  2.480229737536286 -1.3141732874143308 0.9817886281109686]
 ['Rahul Patel' -1.1150795047846587 -1.3345784615195684
  -0.8021580528205214 0.8886156068339726 -0.4665018485317266
  -0.5262635797554441]
 ['Meera Das' 1.0104880837609842 0.818285280392766 1.0948265650851008
  -0.1670468267951125 -0.42129270512465433 0.22776252417776222]
 ['Lakshmi Joshi' -1.8236020342998727 -1.521784004294554
  -1.8321359553259795 0.5800373570039323 -0.22915384564459734
  0.22776252417776222]
 ['Vikram Sharma' 0.3019655542457699 -0.02413966209466918
  -0.33280103395727473 -0.3132154714514474 1.0932135990122653
  -0.5262635797554441]
 ['Rahul Nair' 0.6056180668951473 0.5374769662302876 1.120901955021948
  0.2877000676912626 -1.14463899963781 -1.2802896836886504]
 ['Priya Joshi' -1.317514513217577 -1.1473729187445827
  -0.019896354715110223 -0.1995287478298536 1.5453050330829876
  -0.5262635797554441]
 ['Pooja Patel' -0.0016869584036076392 0.350271423455302
  0.4885737490534071 -0.5405889186946349 1.0140975980498887
  1.7358147320441752]
 ['Manoj Shetty' -1.8236020342998727 -1.521784004294554
  -2.0016259899154853 -0.05336010317351874 -0.5230132777905668
  0.19666866422175366]
 ['Divya Menon' 1.51657560484328 0.005419107817170493 1.3946935493588417
  1.1809528961466425 -0.6360361363082473 0.22776252417776222]
 ['Karthik Reddy' -1.2162970090011178 -1.3345784615195684
  -0.18938638930461596 1.7981093958067227 0.4828901630167902
  0.9817886281109686]
 ['Sneha Patel' -0.5077744794859035 -0.21134520486965477
  -0.6261491707468039 -1.0927815762852333 0.05340330064960405
  -1.2802896836886504]
 ['Sneha Shetty' -1.0138620005681995 -0.7729618331946116
  -1.1346192745153212 1.0347842514903074 -0.6247338504564792
  1.7358147320441752]
 ['Neha Reddy' 0.09953054581285152 0.06946310929282362 0.2278198496849367
  -0.7354804449030814 -1.3254755732660988 0.9817886281109686]
 ['Vivaan Sharma' -0.6089919837023627 -0.585756290419626
  -1.3367035465258856 1.7006636327024995 -1.1898481430448822
  -1.2802896836886504]
 ['Ananya Verma' 1.2129230921939023 1.0990935945552445 0.6124318512534305
  -1.320155023528421 0.9688884546428167 0.9817886281109686]
 ['Priya Joshi' 1.4153581006268208 1.3799019087177227 0.1172768402186223
  1.4083263433898296 -0.353478990014046 -1.2802896836886504]
 ['Deepa Rao' 1.1117055879774431 1.0054908231677517 1.3816558543904183
  0.450109672864968 1.9860941813019422 0.22776252417776222]
 ['Rahul Joshi' -0.06073050252987574 1.4735046801052156
  0.2864894770428425 -1.0602996552504922 1.4887936038241474
  1.7358147320441752]
 ['Pooja Rao' -1.418732017434036 -1.4281812329070611 -0.8934219175994861
  -0.751721405420452 0.18903073087082076 -0.5262635797554441]
 ['Lakshmi Iyer' 0.7068355711116066 0.5374769662302876 1.1665338874114302
  0.38514583079548587 -0.760361280677696 -1.2802896836886504]
 ['Aarav Iyer' 0.6056180668951473 0.6310797376177805 -0.7434884254626156
  0.5637963964865618 0.10991472990844434 -0.5262635797554441]
 ['Priya Menon' 0.7068355711116066 0.350271423455302 0.47553605408498356
  -1.2876731024936798 -0.2404561314963654 -0.5262635797554441]
 ['Manoj Das' -0.06073050252987574 -1.521784004294554 0.1172768402186223
  -0.8166852474899341 0.1212170157602124 1.7358147320441752]
 ['Deepa Naidu' -0.204121966836526 -0.21134520486965477
  0.47553605408498356 -0.32945643196881796 -0.44389727682819047
  0.22776252417776222]
 ['Priya Reddy' -0.06073050252987574 1.0054908231677517
  1.2708354471588184 0.6612421595907851 -1.0994298562307379
  1.7358147320441752]]

In [ ]:
print(x_train)

[['Manoj Nair' -0.204121966836526 -0.02413966209466918 ...
  -2.7656005095743987 0.14382158746374854 1.7358147320441752]
 ['Manoj Rao' 0.5044005626786883 0.44387419484279483 ...
  -1.3363959840457915 0.08731015820490823 0.9817886281109686]
 ['Deepa Sharma' -0.9126444963517402 0.005419107817170493 ...
  2.0742057246020225 -1.4045915742284751 1.7358147320441752]
 ...
 ['Divya Iyer' -0.204121966836526 0.06946310929282362 ...
  1.1971938566640128 -0.3873858475693502 0.9817886281109686]
 ['Vivaan Rao' 1.8202281174926576 1.5671074514927086 ...
  -0.39442027403830004 -0.7942681382330001 -1.2802896836886504]
 ['Rahul Das' 1.2129230921939023 1.1926963659427372 ...
  -1.661215194393202 1.398375317010003 0.22776252417776222]]

In [ ]:
print("Total rows:", len(x))
print("Training rows:", len(x_train))
print("Testing rows:", len(x_test))

Total rows: 200
Training rows: 160
Testing rows: 40